### PR TITLE
21 Implement unit spawner

### LINKED ISSUE #21: Implement unit spawner building
Spawns fighter units

### PR DESCRIPTION
**Pull request by JadenBalogh**
Closes #21. Includes a working queue system and a build UI with progress indicators. Please feel free to suggest additional features if you think they would benefit the usability of the system.

### CODE REVIEW

**Comment by JadenBalogh** [comment]
Now closes #44 as well.

**Review by jpabadir — APPROVED** [review]
Awesome stuff!

**Comment by jpabadir** [comment]
I forgot to mention something, please wait:

**Comment by jpabadir** [comment]
When I run the game, it create a ScriptTemplate.meta file which is new. Do you know if that is a file I should add to the gitignore or something like that?

**Pull request merged**
